#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Author: Leon Jung, Gilbert, Ashe Kim

import rospy
from enum import Enum
from std_msgs.msg import UInt8
from turtlebot3_autorace_msgs.msg import MovingParam


class DetectStop:
    def __init__(self):
        # subscribes state
        self.sub_traffic_sign = rospy.Subscriber(
            "/detect/traffic_sign",
            UInt8,
            self.cbInvokedByTrafficSign,
            queue_size=1,
        )
        self.sub_stop_order = rospy.Subscriber(
            "/detect/stop_order",
            UInt8,
            self.cbStopOrder,
            queue_size=1,
        )
        self.sub_moving_completed = rospy.Subscriber(
            "/control/moving/complete",
            UInt8,
            self.cbMovingComplete,
            queue_size=1,
        )

        # publisher state
        self.pub_stop_return = rospy.Publisher(
            "/detect/stop_stamped", UInt8, queue_size=1
        )
        self.pub_moving = rospy.Publisher(
            "/control/moving/state", MovingParam, queue_size=1
        )

        # STEPS
        self.Step = Enum(
            'Step', 
            (
                'find_obstacle',
                'avoid_obstacle',
                'circling',
                'parking',
                'left',
                'stop',
                'exit'
            )
        )
        self.TrafficSign = Enum(
            "TrafficSign", 
            (
                "circle",
                "left",
                "parking",
                "construction",
                "stop"
            )
        )

        self.is_moving_complete = False
        self.is_stop_detected = False

    def cbInvokedByTrafficSign(self, traffic_sign_type_msg):
        if traffic_sign_type_msg.data == self.TrafficSign.stop.value:
            self.is_stop_detected = True

    def cbMovingComplete(self, data):
        self.is_moving_complete = True

    def cbStopOrder(self, order):
        msg_pub_stop_return = UInt8()
        rospy.loginfo("STOP ORDER")
        if order.data == self.Step.stop.value:
            if self.is_stop_detected == True:
                rospy.loginfo("go straight")
                msg_moving = MovingParam()
                msg_moving.moving_type = 4
                msg_moving.moving_value_angular = 0
                msg_moving.moving_value_linear = 0.1
                self.pub_moving.publish(msg_moving)
                while True:
                    if self.is_moving_complete == True:
                        break
                self.is_moving_complete = False

                rospy.sleep(5)



            rospy.loginfo("moving finished")
            msg_pub_stop_return.data = (
                self.Step.exit.value
            )

        elif order.data == self.Step.exit.value:
            rospy.loginfo("Now finished")
            rospy.sleep(2)
            msg_pub_stop_return.data = (
                self.Step.exit.value
            )

        self.pub_stop_return.publish(msg_pub_stop_return)
        rospy.sleep(3)

    def main(self):
        rospy.spin()


if __name__ == "__main__":
    rospy.init_node("detect_stop")
    node = DetectStop()
    node.main()